version: '3'
services:
    web:
        image: ghcr.io/gewis/gewisdb:latest
        volumes:
            - public:/code/public
            - data:/code/data
        networks:
            - gewisdb

    nginx:
        image: nginx:alpine
        volumes:
            - public:/code/public
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
        networks:
            - gewisdb

    postgres:
        image: postgres:9.6-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: gewisdb
            POSTGRES_USER: gewisdb
        networks:
            - gewisdb

networks:
    gewisdb:
        driver: bridge

volumes:
    public:
    data:
    postgres:
