version: '2'
services:
  nginx:
    ports:
      - "80:80"
  admin:
    image: dockage/phppgadmin:latest
    ports:
      - "8000:80"
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
    networks:
      - gewisdb
