version: '3.5'

services:
    postgresql:
        image: postgres:9.6-alpine
        env_file:
            - .env
        volumes:
            - gewisdb_postgres:/var/lib/postgresql/data:rw
        networks:
            - gewisdb_network
        ports:
            - "5432:5432"
        restart: unless-stopped
    phppgadmin:
        image: bitnami/phppgadmin:latest
        env_file:
            - .env
        depends_on:
            - postgresql
        networks:
            - gewisdb_network
        ports:
            - "8080:8080"
        restart: unless-stopped
    nginx:
        build: docker/nginx
        ports:
            - "80:9200"
            - "81:9201"
            - "82:9202"
    web:
        image: abc-db.docker-registry.gewis.nl/gewisdb_web:development
        build:
            dockerfile: docker/web/development/Dockerfile
            context: .
        depends_on:
            - postgresql

volumes:
    gewisdb_postgres:
