version: '3'
services:
    # Uncomment for a development setup with mounted codebase:
    # web:
    #     build: docker
    #     volumes:
    #         - .:/code
  nginx:
    ports:
      - "80:80"
  admin:
    image: dockage/phppgadmin:latest
    ports:
      - "8000:80"
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
    networks:
      - gewisdb
