name: PHP Static Analysis with PHPStan

# Only run this action on pull requests (creation, synchronisation, and reopening).
on: [pull_request]

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest

        # Create a Postgres service.
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: gewisdb
                    POSTGRES_USER: gewisdb
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   name: Checkout head branch
                uses: actions/checkout@v3

            -   name: Install PostgreSQL client
                run: |
                    sudo apt-get update
                    sudo apt-get install --yes --no-install-recommends postgresql-client

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
                    extensions: calendar, curl, intl, opcache, pgsql, pdo_pgsql, zip, memcached, xdebug
                    tools: cs2pr

            -   name: Get Composer cache directory
                id: composer-cache-head
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache-head.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Extract configuration files
                run: |
                    cp config/autoload/doctrine.local.development.php.dist config/autoload/doctrine.local.php
                    cp config/autoload/laminas-developer-tools.local.php.dist config/autoload/laminas-developer-tools.local.php
                    cp config/autoload/local.development.php.dist config/autoload/local.php

            -   name: Check out master
                run: |
                    git fetch --all
                    git update-ref refs/heads/temp-phpstanpr refs/remotes/origin/master
                    git checkout --detach temp-phpstanpr

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Load environment variables
                uses: c-py/action-dotenv-to-setenv@v3
                with:
                    env-file: .env.dist

            -   name: Create databases
                env:
                    DOCTRINE_DEFAULT_HOST: 127.0.0.1
                    DOCTRINE_REPORT_HOST: 127.0.0.1
                    PGPASSWORD: gewisdb
                run: |
                    psql -h $DOCTRINE_REPORT_HOST -p 5432 -U gewisdb -c "CREATE DATABASE $DOCTRINE_REPORT_DATABASE"
                    ./orm orm:schema-tool:update --force
                    EM_ALIAS=orm_report ./orm orm:schema-tool:update --force

            -   name: Generate PHPStan Baseline
                env:
                    DOCTRINE_DEFAULT_HOST: 127.0.0.1
                    DOCTRINE_REPORT_HOST: 127.0.0.1
                run: |
                    echo "" > phpstan/phpstan-baseline.neon
                    echo "" > phpstan/phpstan-baseline-pr.neon
                    vendor/bin/phpstan analyse -c phpstan.neon --generate-baseline phpstan/phpstan-baseline-temp.neon --memory-limit 1G --no-progress

            -   name: Check out new branch
                run: |
                    git checkout -- phpstan/phpstan-baseline.neon
                    git checkout --theirs -- config/modules.config.php
                    git checkout -

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Load environment variables
                uses: c-py/action-dotenv-to-setenv@v3
                with:
                    env-file: .env.dist

            -   name: Create databases
                env:
                    DOCTRINE_DEFAULT_HOST: 127.0.0.1
                    DOCTRINE_REPORT_HOST: 127.0.0.1
                    PGPASSWORD: gewisdb
                run: |
                    ./orm orm:schema-tool:update --force
                    EM_ALIAS=orm_report ./orm orm:schema-tool:update --force

            -   name: Run PHPStan
                env:
                    DOCTRINE_DEFAULT_HOST: 127.0.0.1
                    DOCTRINE_REPORT_HOST: 127.0.0.1
                run: |
                    cp phpstan/phpstan-baseline-temp.neon phpstan/phpstan-baseline-pr.neon
                    vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 1G --no-progress --error-format=checkstyle | cs2pr
